site_name: MINIMOD Optimization Tool
nav:
  - Home: index.md
  - Base Classes: base.md
  - Solvers: solvers.md
  - Utility Classes: utils.md
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
plugins:
  - git-revision-date-localized
  - search
  - mkdocstrings
repo_url: https://github.com/minimod-nutrition/minimod
