site_name: MINIMOD Optimization Tool
nav:
  - Home: index.md
  - API Reference: api.md
theme:
  name: material
plugins:
  - git-revision-date-localized
  - search
  - mkdocstrings
  
repo_url: https://github.com/minimod-nutrition/minimod
