name: publish site
on:
  push:
    branches:
      - master 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r reqs/base-requirements.txt
      - run: pip install mkdocs-material 
      - run: pip install mkdocstrings-python
      - run: pip install mkdocstrings
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pwd
      - run: mkdocs gh-deploy --force
